lib/propollr_web/router.ex
defmodule PropollrWeb.Router do
  use PropollrWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(PropollrWeb.Plugs.Veil.UserId)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", PropollrWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    post("/feedback", PageController, :feedback)
    post("/contact", PageController, :contact)

    # Sessions
    get("/sesh", SeshController, :view)
    post("/sesh/join", SeshController, :join)
    get("/sesh/join/:sesh_id", SeshController, :join)

    get("/sesh/new", SeshController, :new)
    get("/sesh/new/soft", SeshController, :new_soft)
    post("/sesh/new", SeshController, :create)
    post("/sesh/new/soft", SeshController, :create_soft)

    # Questions
    post("/question", QuestionController, :answer)
  end

  # Other scopes may use custom stacks.
  # scope "/api", PropollrWeb do
  #   pipe_through :api
  # end

  # Default Routes for Veil
  scope "/veil", PropollrWeb.Veil do
    pipe_through(:browser)

    post("/users", UserController, :create)

    get("/users/new", UserController, :new)
    get("/sessions/new/:request_id", SessionController, :create)
    get("/sessions/signout/:session_id", SessionController, :delete)
  end

  # Add your routes that require authentication in this block.
  # Alternatively, you can use the default block and authenticate in the controllers.
  # See the Veil README for more.
  scope "/", PropollrWeb do
    pipe_through([:browser, PropollrWeb.Plugs.Veil.Authenticate])
    # Dashboard
    get("/dashboard", DashboardController, :index)

    # Seshes
    get("/sesh/close", SeshController, :close)
    get("/sesh/reopen", SeshController, :reopen)
    get("/sesh/edit", SeshController, :edit)
    put("/sesh/edit", SeshController, :update)

    # Questions
    get("/question", QuestionController, :new)
    post("/question/new", QuestionController, :create)
    get("/quesiton/edit", QuestionController, :edit)
    put("/question", QuestionController, :update)
    delete("/question", QuestionController, :delete)
  end
end

lib/propollr_web/templates/page/index.html.eex
<section class="hero is-primary is-medium is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">Welcome to ProPollr</h1>
      <h2 class="subtitle">A dead simple realtime polling application</h2>
    </div>
  </div>
</section>
<%= render PropollrWeb.LayoutView, "flash.html", conn: @conn %>
<section class="hero is-medium">
  <div class="hero-body">
    <div class="container">
      <div class="row">
        <div class="columns">
          <div class="column">
            <%= if @conn.assigns[:session_unique_id] do %>
              <p class="subtitle">You are already logged in.</p>
              <%= link "Go to Dashboard", to: dashboard_path(@conn, :index), class: "button is-primary is-outlined" %>
            <% else %>
              <p class="subtitle">Start a Session / Visit Your Dashboard</p>
              <p>
                No Passwords to remember. Just your email address.
              </p>
              <%= form_for @conn, user_path(@conn, :create), [as: :user], fn f -> %>
                <div class="field">
                  <label class="label">Email:</label>
                  <div class="control">
                    <%= text_input f, :email, class: "input", placeholder: "me@mydomain.com" %>
                  </div>
                </div>
                <div class="field">
                  <div class="control">
                    <%= submit "Go!", class: "button is-primary is-fullwidth" %>
                  </div>
                </div>
              <% end %>        
            <% end %>
          </div>
          <div class="is-divider-vertical" data-content="OR"></div>
          <div class="column">
            <p class="subtitle">Join a Session</p>
            <p>As long as the session is open, you can rejoin.</p>
            <%= form_for @conn, sesh_path(@conn, :join), fn f -> %>
              <div class="field">
                <label class="label">Session ID</label>
                <div class="control">
                  <%= text_input f, :sesh_id, class: "input", placeholder: "Session ID" %>
                </div>
              </div>
              <div class="field">
                <div class="control">
                  <%= submit "Join Session", class: "button is-fullwidth is-info is-outlined" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="hero-foot">
    <div class="container">
      <div class="has-text-centered">
        <span class="icon fa-2x">
          <i class="fas fa-chevron-circle-down fa-stack-1x fa-inverse animated bounce has-text-primary"></i>
        </span>
      </div>
    </div>
  </div>
</section>
<%= render "marketing.html", conn: @conn %>

lib/propollr_web/templates/page/marketing.html.eex
<section class="hero is-primary is-bold is-medium">
  <div class="hero-body">
    <div class="container">
      <div class="columns">
        <div class="column">
          <p class="title">ProPollr is</p>
          <div class="content">
            A tool for real-time collaboration with a focus on honest and anonymous feedback.
            Our main goal is to create an atmosphere where 
            We aim to invoke honest conversations which drive better discussions.
          </div>
        </div>
        <div class="column">
          <p class="title">ProPollr is Not</p>
          <div class="content">
            A replacement for traditional forms where you want to associate answers with a name.
            Picture taking orders for lunch.
          </div>
        </div>
      </div>
    </div> 
  </div>
</section>
<section class="section">
  <div class="container">
    <p class="title has-text-centered">Examples</p>
    <p class="subtitle has-text-centered">A Few Ideas</p>
    <div class="columns">
      <div class="column">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title">Presentations</p>
          </header>
          <div class="card-content">
            <div class="content">
              Pre-Poll your attendees in order to cater your talk to ther experience levels.
              Keep them captivated for longer!
            </div>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title">Group Polling</p>
          </header>
          <div class="card-content">
            <div class="content">
              FaceBook groups allow for polls, but names are attached.
              This can cause a lack of answering.
              Gain more confidence in your polling!
            </div>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title">Group Decisions</p>
          </header>
          <div class="card-content">
            <div class="content">
              Want to assign points to a card? Ask the team instead of doing it manually.
              Let them answer on their own time and aggregate the results.
            </div>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="card">
          <header class="card-header">
            <p class="card-header-title">Retros</p>
          </header>
          <div class="card-content">
            <div class="content">
              What is working and what is not? Perform retros with your team.
              Identify action items and make the appropriate changes.
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>
<section class="hero features is-primary is-bold is-medium">
  <div class="container">
    <div class="hero-body">
      <p class="title has-text-centered">Features</p>
      <p class="subtitle has-text-centered">Less is More!</p>
      <div class="columns">
        <div class="column">
          <div class="card">
            <header class="card-header">
              <p class="card-header-title">
                Simplistic Interface
              </p>
              <span class="card-header-icon">
                <span class="icon">
                  <i class="fas fa-browser"></i>
                </span>
              </span>
            </header>
            <div class="card-content">
              <div class="content">
                Focus on what really matters, your discussions.
                Don't get lost in the technology!
              </div>
            </div>
          </div>
        </div>
        <div class="column">
          <div class="card">
            <header class="card-header">
              <p class="card-header-title">
                Anonymous Polling
              </p>
              <span class="card-header-icon">
                <span class="icon">
                  <i class="fas fa-user-secret"></i>
                </span>
              </span>
            </header>
            <div class="card-content">
              <div class="content">
                We believe that anonyminity leads to honest feedback.
                By having pollrs remain anonymous, there is no fear of consequences for speaking their mind.
              </div>
            </div>
          </div>
        </div>
        <div class="column">
          <div class="card">
            <header class="card-header">
              <p class="card-header-title">
                Real-Time Capabilities
              </p>
              <span class="card-header-icon">
                <span class="icon">
                  <i class="fas fa-clock"></i>
                </span>
              </span>
            </header>
            <div class="card-content">
              <div class="content">
                Ask questions, get answers, all in real-time.
                Dynamically shape your discussions and move them in a constructive manner.
              </div>
            </div>
          </div>
        </div>
        <div class="column">
          <div class="card">
            <header class="card-header">
              <p class="card-header-title">
                Scalable
              </p>
              <span class="card-header-icon">
                <span class="icon">
                  <i class="fas fa-users"></i>
                </span>
              </span>
            </header>
            <div class="card-content">
              <div class="content">
                ProPollr can handle all of your polling needs, from small teams to large organizations.
                All without compromising the basic values of ProPollr.
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="hero-footer">
        <p class="has-text-centered">
          More Coming!
        </p>
      </div>
    </div>
  </div>
</section>
<section class="section is-medium">
  <div class="container">
    <p class="title has-text-centered">How It Works</p>
    <p class="subtitle has-text-centered">It is <em>Really</em> this Simple</p>
    <div class="steps is-large">
      <div class="step-item is-completed is-primary">
        <div class="step-marker">
          <span class="icon">
            <i class="fas fa-sign-in"></i>
          </span>
        </div>
        <div class="step-details">
          <p class="step-title is-completed">Step 1</p>
          <p>Log In or Create an Account</p>
        </div>
      </div>
      <div class="step-item is-completed">
        <div class="step-marker">
          <span class="icon">
            <i class="fas fa-plus"></i>
          </span>
        </div>
        <div class="step-details">
          <p class="step-title">Step 2</p>
          <p>Create a Sesh</p>
        </div>
      </div>
      <div class="step-item is-completed">
        <div class="step-marker">
          <span class="icon">
            <i class="fas fa-users"></i>
          </span>
        </div>
        <div class="step-details">
          <p class="step-title">Step 3</p>
          <p>Invite Users to Your Sesh.</p>
        </div>
      </div>
      <div class="step-item is-completed">
        <div class="step-marker">
          <span class="icon">
            <i class="fas fa-comment-plus"></i>
          </span>
        </div>
        <div class="step-details">
          <p class="step-title">Step 4</p>
          <p>Ask Questions and Get Real-Time Feedback</p>
        </div>
      </div>
    </div>
    <div class="has-text-centered">
      <%= link "Get Started", to: user_path(@conn, :new), class: "button is-primary is-outlined is-large" %>
    </div>
  </div>
</section>

<section class="hero is-primary is-bold">
  <div class="hero-body">
    <div class="container">
      <p class="subtitle has-text-centered">
        Sign Up to Recieve News From Us!
      </p>
      <form action="https://alphaity.us10.list-manage.com/subscribe/post?u=754435ba61eff39080741959c&amp;id=e2ce392544" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
        <div class="field is-grouped">
          <p class="control is-expanded">
            <input type="email" value="" name="EMAIL" class="input" id="mce-EMAIL" placeholder="email address" required>
            <div style="position: absolute; left: -5000px;" aria-hidden="true">
              <input type="text" name="b_754435ba61eff39080741959c_e2ce392544" tabindex="-1" value="">
            </div>
          </p>
          <p class="control">
            <a class="button is-light is-outlined" onclick="document.querySelector('#mc-embedded-subscribe-form').submit()">
              <span class="icon">
                <i class="fas fa-envelope"></i>
              </span>
              <span>Sign Up</span>
            </a>
          </p>
        </div>
      </form>
      <p class="help has-text-centered">
        We will only use your email for ProPollr news and info.
      </p>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <%= form_for @conn, page_path(@conn, :contact), [id: "contact-form"], fn f -> %>
      <p class="title has-text-centered">
        Contact Us!
      </p>
      <p class="subtitle has-text-centered">
        We Love Hearing from You
      </p>
      <div class="card">
        <div class="card-content">
          <div class="field">
            <p class="control">
              <%= label f, :email, "Email", class: "label" %>
              <%= email_input f, :email, placeholder: "me@mydomain.com", required: true, class: "input" %>
            </p>
            <div class="field">
              <p class="control">
                <%= label f, :message, "Message", class: "label" %>
                <%= textarea f, :message, placeholder: "My Message", required: true, class: "textarea" %>
              </p>
            </div>
          </div>
        </div>
        <footer class="card-footer">
          <p class="card-footer-item">
            <%= submit class: "button is-primary is-fullwidth is-outlined" do %>
              <span class="icon">
                <i class="fas fa-envelope"></i>
              </span>
              <span>Send</span>
            <% end %>
          </p>
        </footer>
      </div>
    <% end %>
  </div>
</section>