lib/propollr_web/router.ex
defmodule PropollrWeb.Router do
  use PropollrWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(PropollrWeb.Plugs.Veil.UserId)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", PropollrWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    post("/feedback", PageController, :feedback)
    post("/contact", PageController, :contact)

    # Sessions
    get("/sesh", SeshController, :view)
    post("/sesh/join", SeshController, :join)
    get("/sesh/join/:sesh_id", SeshController, :join)

    get("/sesh/new", SeshController, :new)
    get("/sesh/new/soft", SeshController, :new_soft)
    post("/sesh/new", SeshController, :create)
    post("/sesh/new/soft", SeshController, :create_soft)

    # Questions
    post("/question", QuestionController, :answer)
  end

  # Other scopes may use custom stacks.
  # scope "/api", PropollrWeb do
  #   pipe_through :api
  # end

  # Default Routes for Veil
  scope "/veil", PropollrWeb.Veil do
    pipe_through(:browser)

    post("/users", UserController, :create)

    get("/users/new", UserController, :new)
    get("/sessions/new/:request_id", SessionController, :create)
    get("/sessions/signout/:session_id", SessionController, :delete)
  end

  # Add your routes that require authentication in this block.
  # Alternatively, you can use the default block and authenticate in the controllers.
  # See the Veil README for more.
  scope "/", PropollrWeb do
    pipe_through([:browser, PropollrWeb.Plugs.Veil.Authenticate])
    # Dashboard
    get("/dashboard", DashboardController, :index)

    # Seshes
    get("/sesh/close", SeshController, :close)
    get("/sesh/reopen", SeshController, :reopen)
    get("/sesh/edit", SeshController, :edit)
    put("/sesh/edit", SeshController, :update)

    # Questions
    get("/question", QuestionController, :new)
    post("/question/new", QuestionController, :create)
    get("/quesiton/edit", QuestionController, :edit)
    put("/question", QuestionController, :update)
    delete("/question", QuestionController, :delete)
  end
end

lib/propollr_web/controllers/sesh_controller.ex
defmodule PropollrWeb.SeshController do
  use PropollrWeb, :controller
  alias Propollr.Seshes.Sesh
  alias Propollr.Veil.User

  def view(conn, %{"sesh_id" => sesh_id}) do
    user = User.get(conn.assigns.veil_user_id)
    sesh = Sesh.get_by(sesh_id)

    conn
    |> put_session(:sesh_id, sesh.sesh_id)
    |> render("view.html", sesh: sesh, user: user)
  end

  def join(conn, %{"sesh_id" => sesh_id}) do
    sesh = Sesh.get_by(sesh_id)

    case sesh do
      nil ->
        conn
        |> put_flash(:error, "No session with the ID " <> sesh_id <> " exists or is open.")
        |> redirect(to: page_path(conn, :index))

      _ ->
        conn
        |> put_session(:sesh_id, sesh.sesh_id)
        |> render("view.html", sesh: sesh)
    end
  end

  def join(conn, params) do
    sesh_id = params["sesh_id"]
    sesh = Sesh.get_by(sesh_id)

    case sesh do
      nil ->
        conn
        |> put_flash(:error, "No Sesh with the ID " <> sesh_id <> " exists or is open.")
        |> redirect(to: page_path(conn, :index))

      _ ->
        conn
        |> put_session(:sesh_id, sesh.sesh_id)
        |> render("view.html", sesh: sesh)
    end
  end

  def close(conn, %{"sesh_id" => sesh_id}) do
    case Sesh.close(sesh_id) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Sesh Closed")
        |> redirect(to: sesh_path(conn, :view, sesh_id: sesh_id))

      {:error, message} ->
        conn
        |> put_flash(:error, "Sesh unable to close - " <> message)
        |> redirect(to: sesh_path(conn, :view, sesh_id: sesh_id))
        |> halt()
    end
  end

  def reopen(conn, %{"sesh_id" => sesh_id}) do
    case Sesh.reopen(sesh_id) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Sesh Reopened")
        |> redirect(to: sesh_path(conn, :view, sesh_id: sesh_id))

      {:error, message} ->
        conn
        |> put_flash(:error, "Sesh unable to reopen - " <> message)
        |> redirect(to: sesh_path(conn, :view, sesison_id: sesh_id))
        |> halt()
    end
  end

  def new(conn, _params) do
    user = User.get(conn.assigns.veil_user_id)

    changeset =
      user
      |> Ecto.build_assoc(:seshes, %Sesh{})
      |> Sesh.changeset(%{})

    render(conn, "new.html", changeset: changeset, user: user)
  end

  def new_soft(conn, _params) do
    render(conn, "new_soft.html", changeset: Sesh.changeset(%Sesh{}, %{}))
  end

  def create(conn, %{"sesh_params" => sesh_params}) do
    user = User.get(conn.assigns.veil_user_id)

    case Sesh.create(user, sesh_params) do
      {:ok, sesh} ->
        conn
        |> put_flash(:info, "Sesh Created!")
        |> redirect(to: sesh_path(conn, :view, sesh_id: sesh.sesh_id))

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Error creating session")
        |> render("new.html", changeset: changeset)
        |> halt()
    end
  end

  def edit(conn, %{"sesh_id" => sesh_id}) do
    sesh =
      sesh_id
      |> Sesh.get_by()

    changeset =
      sesh
      |> Sesh.changeset(%{})

    render(conn, "edit.html", changeset: changeset, sesh_id: sesh_id, questions: sesh.questions)
  end

  def update(conn, %{"sesh_id" => sesh_id, "sesh_params" => sesh_params}) do
    case Sesh.update(sesh_id, sesh_params) do
      {:ok, sesh} ->
        user = sesh.user_id |> User.get()

        conn
        |> put_flash(:info, "Sesh Updated")
        |> redirect(to: sesh_path(conn, :view, sesh_id: sesh_id, user: user))

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Error when updating. Please try again")
        |> render("edit.html", changeset: changeset)
        |> halt()
    end
  end
end

lib/propollr_web/views/sesh_view.ex
defmodule PropollrWeb.SeshView do
  use PropollrWeb, :view
  alias Propollr.Repo
  alias Propollr.Veil.User

  def user_belongs_to_session?(conn) do
    case conn.assigns[:user] do
      nil ->
        false

      user ->
        Enum.any?(user.seshes, fn sesh ->
          sesh.sesh_id == conn.query_params["sesh_id"]
        end)
    end
  end
end

lib/propollr_web/templates/sesh/edit.html.eex
<section class="hero is-primary is-bold">
  <div class="hero-body">
    <h1 class="title">Editing Session</h1>
  </div>
</section>
<%= render PropollrWeb.LayoutView, "flash.html", conn: @conn %>
<section class="section">
  <div class="container">
    <%= breadcrumbs [@conn, :sesh_edit, @sesh_id] %>
    <%= form_for @changeset, sesh_path(@conn, :update, sesh_id: @sesh_id), [as: :sesh_params, method: :put, id: "update-form"], fn f -> %>
      <div class="card">
        <div class="card-content">
          <div class="field">
            <label class="label">Title</label>
            <div class="control">
              <%= text_input f, :title, class: "input" %>
            </div>
          </div>
        </div>
        <footer class="card-footer">
          <div class="card-footer-item">
            <a onclick="document.getElementById('update-form').submit()" class="button is-primary is-outlined">
              <span class="icon">
                 <i class="fas fa-save"></i>
              </span>
              <span>Update</span>
            </a>
          </div>
          <div class="card-footer-item">
            <%= link to: sesh_path(@conn, :view, sesh_id: @sesh_id), class: "button is-info is-outlined" do %>
              <span class="icon">
                 <i class="fas fa-undo-alt"></i>
              </span>                
              <span>Back</span>
            <% end %>
          </div>
        </footer>
      </div>
    <% end %>

    <h3 class="subtitle">Edit Questions</h3>
    <div class="columns is-multiline">
      <%= for question <- @questions do %>
        <div class="column is-one-quarter">
          <div class="card question" id="question_id_${question.id}">
            <header class="header">
                <p class="card-header-title">
                    <%= question.text %>
                </p>
            </header>
            <div class="card-content">
              <div class="field">
                <div class="control">
                  <div class="select is-fullwidth">
                    <select>
                      <option></option>
                      <%= for option <- question.options do %>
                        <option><%= option %></option>
                      <% end %>
                    </select>
                  </div>
                </div>
              </div>
            </div>
            <footer class="card-footer">
              <div class="card-footer-item">
                <%= link to: question_path(@conn, :edit, question_id: question.id), class: "button is-info is-outlined" do %>
                  <span class="icon">
                     <i class="fas fa-wrench"></i>
                  </span>      
                  <span>Edit</span>
                  <% end %>
              </div>
              <div class="card-footer-item">
                <%= link to: question_path(@conn, :delete, sesh_id: @sesh_id, question_id: question.id), class: "button is-danger is-outlined", method: :delete, data: [confirm: "Are you sure you want to delete this question?"] do %>
                  <span class="icon">
                     <i class="fas fa-times"></i>
                  </span>                 
                  <span>Delete</span>
                <% end %>
              </div>
            </footer>
          </div>
        </div>
      <% end %> 
    </div>
  </div>
</section>

lib/propollr_web/templates/sesh/new.html.eex
<section class="hero is-primary is-medium is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">Creating a new Session</h1>
    </div>
  </div>
</section>
<%= render PropollrWeb.LayoutView, "flash.html", conn: @conn %>
<section class="section">
  <div class="container">
    <%= form_for @changeset, sesh_path(@conn, :create), [as: :sesh_params, id: "new-session-form"], fn f -> %>
    <div class="card">
      <div class="card-content">
        <div class="field">
          <label class="label">Title</label>
          <div class="control">
            <%= text_input f, :title, class: "input" %>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <div class="card-footer-item">
          <a onclick="document.getElementById('new-session-form').submit()" class="button is-primary is-outlined">
            <span class="icon">
               <i class="fas fa-plus"></i>
            </span>
            <span>Add</span>
        </a>
        </div>
        <div class="card-footer-item">
          <%= link to: dashboard_path(@conn, :index), class: "button is-warning is-outlined" do %>
            <span class="icon">
               <i class="fas fa-ban"></i>
            </span>          
            <span>Cancel</span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</section>

lib/propollr_web/templates/sesh/new_soft.html.eex
<%= render PropollrWeb.LayoutView, "flash.html", conn: @conn %>
<section class="section">
  <div class="container">
    <h1 class="title">Creating a new Session</h1>
      <%= form_for @changeset, sesh_path(@conn, :create_soft), [as: :sesh_params], fn f -> %>
      <div class="card">
        <div class="card-content">
          <div class="field">
            <label class="label">Title</label>
            <div class="control">
              <%= text_input f, :title, class: "input" %>
            </div>
          </div>
          <div class="columns">
            <div class="column">
              <div class="field">
                <div class="control">
                  <%= submit "Create", class: "button" %>
                </div>
              </div>
            </div>
            <div class="column">
              <div class="field">
                <div class="control is-pulled-right">
                  <%= link "Cancel", to: page_path(@conn, :index), class: "button" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

lib/propollr_web/templates/sesh/view.html.eex
<%= render PropollrWeb.LayoutView, "flash.html", conn: @conn %>
<section class="section">
  <div class="container">
  <%= breadcrumbs [@conn, :sesh, @sesh.sesh_id] %>
    <div class="card session-info">
      <header class="header">
        <p class="card-header-title <%= if @sesh.closed, do: "has-text-danger", else: "has-text-success" %> ">
          <%= @sesh.title %> |  <%= if @sesh.closed, do: "Closed", else: "Open" %>
        </p>
      </header>
      <div class="card-content">
        <h4 class="subtitle">Sesh ID: <%= @sesh.sesh_id %></h4>
        <p>
          Created at: <%= @sesh.inserted_at %>
          <br>
          Last Updated: <%= @sesh.updated_at %>
          <br>
          Questions: <%= length(@sesh.questions) %>
          <br>
          <%= if user_belongs_to_session?(@conn) do %>
            Pollrs Online: <span class="pollr-count"></span>
            <br>
          <% end %>
          <span id="share-link-container-<%= @sesh.sesh_id %>">
            <a onclick="copy_share_link('<%= PropollrWeb.Endpoint.url() <> "/sesh/join/" %>', '<%= @sesh.sesh_id %>')" class="button is-info is-outlined share-link">
                 <span class="icon">
                     <i class="fas fa-copy"></i>
                 </span>
                 <span class="copy-share-link">Share Link</span>
            </a>
          </span>
        </p>
      </div>
      <footer class="card-footer is-block-mobile">
       <%= if user_belongs_to_session?(@conn) do %>
       <div class="card-footer-item">
        <%= link to: question_path(@conn, :new, sesh_id: @sesh.sesh_id), class: "button is-primary is-outlined is-fullwidth" do %>
          <span class="icon">
             <i class="fas fa-question"></i>
          </span>
          <span>Create Question</span>
        <% end %>
      </div>
      <div class="card-footer-item">
        <%= link to: sesh_path(@conn, :edit, sesh_id: @sesh.sesh_id), class: "button is-info is-outlined is-fullwidth" do %>
          <span class="icon">
             <i class="fas fa-edit"></i>
          </span>
          <span>Edit Session</span>        
        <% end %>
      </div>
      <div class="card-footer-item">
        <%= if @sesh.closed do %>
          <%= link to: sesh_path(@conn, :reopen, sesh_id: @sesh.sesh_id), class: "button is-success is-outlined is-fullwidth" do %>
            <span class="icon">
               <i class="fas fa-plus"></i>
            </span>
            <span>Re-Open Session</span>   
          <% end %>        
        <% else %>
          <%= link to: sesh_path(@conn, :close, sesh_id: @sesh.sesh_id), class: "button is-danger is-outlined is-fullwidth" do %>
            <span class="icon">
               <i class="fas fa-times"></i>
            </span>
            <span>Close Session</span>    
          <% end %>
        <% end %>
      </div>
      <% end %>
    </footer>
    </div>

    <%= if !user_belongs_to_session?(@conn) do %>
      <h1 class="title">Questions</h1>
      <div class="questions columns is-multiline"></div>    
    <% end %>

      <h1 class="title">Answers</h1>
      <div class="answers columns is-multiline"></div>
  </div>
</section>

<script>window.user = <%= if @conn.assigns[:user], do: true, else: false %></script>
<script>window.sesh_id = "<%= Plug.Conn.get_session(@conn, :sesh_id) %>";</script>